server:
  port: 8000

spring:
  application:
    name: VideosApplication
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/code_micro_videos?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  liquibase:
    change-log: classpath:db/master.yaml
    contexts: dev, local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
